// src/features/platform/pages/PlatformUsers.tsx
import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Search, Plus, X, Shield, Headphones, Code, TrendingUp, MoreVertical } from 'lucide-react'

type Role = 'SUPER_ADMIN' | 'SUPPORT' | 'DEVOPS' | 'SALES'
type Status = 'ACTIVE' | 'INACTIVE'

interface PUser {
  id: string
  name: string
  email: string
  role: Role
  status: Status
  lastLogin: string
  createdAt: string
}

const roleConfig: Record<Role, { icon: React.ElementType; color: string; label: string }> = {
  SUPER_ADMIN: { icon: Shield, color: 'var(--warning)', label: 'Super Admin' },
  SUPPORT: { icon: Headphones, color: 'var(--info)', label: 'Soporte' },
  DEVOPS: { icon: Code, color: 'var(--success)', label: 'DevOps' },
  SALES: { icon: TrendingUp, color: 'var(--warning)', label: 'Ventas' },
}

const initialUsers: PUser[] = [
  {
    id: '1',
    name: 'Carlos Herrera',
    email: 'carlos@saas.com',
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    lastLogin: 'Hoy 12:36',
    createdAt: '01 Ene 2026',
  },
  {
    id: '2',
    name: 'Ana Martínez',
    email: 'ana@saas.com',
    role: 'SUPPORT',
    status: 'ACTIVE',
    lastLogin: 'Hoy 09:14',
    createdAt: '15 Ene 2026',
  },
  {
    id: '3',
    name: 'Luis Ramírez',
    email: 'luis@saas.com',
    role: 'DEVOPS',
    status: 'ACTIVE',
    lastLogin: 'Ayer 22:05',
    createdAt: '20 Ene 2026',
  },
  {
    id: '4',
    name: 'María Torres',
    email: 'maria@saas.com',
    role: 'SALES',
    status: 'ACTIVE',
    lastLogin: 'Hace 2 días',
    createdAt: '01 Feb 2026',
  },
  {
    id: '5',
    name: 'Pedro Gómez',
    email: 'pedro@saas.com',
    role: 'SUPPORT',
    status: 'INACTIVE',
    lastLogin: 'Hace 2 semanas',
    createdAt: '10 Feb 2026',
  },
]

export default function PlatformUsers() {
  const [users, setUsers] = useState<PUser[]>(initialUsers)
  const [search, setSearch] = useState('')
  const [showModal, setShowModal] = useState(false)
  const [editing, setEditing] = useState<PUser | null>(null)
  const [openMenu, setOpenMenu] = useState<string | null>(null)
  const [toast, setToast] = useState('')
  const [form, setForm] = useState({ name: '', email: '', role: 'SUPPORT' as Role })

  const filtered = users.filter(
    (u) =>
      u.name.toLowerCase().includes(search.toLowerCase()) ||
      u.email.toLowerCase().includes(search.toLowerCase())
  )

  const showToast = (msg: string) => {
    setToast(msg)
    setTimeout(() => setToast(''), 3000)
  }

  const openCreate = () => {
    setForm({ name: '', email: '', role: 'SUPPORT' })
    setEditing(null)
    setShowModal(true)
  }
  const openEdit = (u: PUser) => {
    setForm({ name: u.name, email: u.email, role: u.role })
    setEditing(u)
    setShowModal(true)
    setOpenMenu(null)
  }

  const toggleStatus = (u: PUser) => {
    setUsers((us) =>
      us.map((x) =>
        x.id === u.id ? { ...x, status: x.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE' } : x
      )
    )
    showToast(`${u.name} ${u.status === 'ACTIVE' ? 'desactivado' : 'activado'}`)
    setOpenMenu(null)
  }

  const deleteUser = (u: PUser) => {
    setUsers((us) => us.filter((x) => x.id !== u.id))
    showToast(`${u.name} eliminado`)
    setOpenMenu(null)
  }

  const save = () => {
    if (editing) {
      setUsers((us) => us.map((x) => (x.id === editing.id ? { ...x, ...form } : x)))
      showToast('Cambios guardados')
    } else {
      setUsers((us) => [
        {
          id: Date.now().toString(),
          ...form,
          status: 'ACTIVE',
          lastLogin: 'Nunca',
          createdAt: 'Hoy',
        },
        ...us,
      ])
      showToast('Usuario creado')
    }
    setShowModal(false)
  }

  const roleCounts = (Object.keys(roleConfig) as Role[]).map((r) => ({
    role: r,
    count: users.filter((u) => u.role === r).length,
    ...roleConfig[r],
  }))

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1
            className="text-2xl font-black"
            style={{ color: 'var(--text-primary)', fontFamily: 'var(--font-heading)' }}
          >
            Usuarios de Plataforma
          </h1>
          <p className="mt-0.5 text-sm" style={{ color: 'var(--text-muted)' }}>
            Administra los accesos al panel de gestión
          </p>
        </div>
        <button
          onClick={openCreate}
          className="flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold"
          style={{
            background: 'var(--accent)',
            color: 'var(--text-on-primary)',
            boxShadow: 'var(--shadow-glow)',
          }}
        >
          <Plus size={16} /> Nuevo Usuario
        </button>
      </div>

      {/* Role cards */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        {roleCounts.map((r) => (
          <div
            key={r.role}
            className="flex items-center gap-3 rounded-2xl p-4"
            style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
          >
            <div
              className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-xl"
              style={{ background: `${r.color}15`, color: r.color }}
            >
              <r.icon size={18} />
            </div>
            <div>
              <p
                className="text-xl leading-none font-black"
                style={{ color: 'var(--text-primary)' }}
              >
                {r.count}
              </p>
              <p className="mt-0.5 text-xs" style={{ color: 'var(--text-muted)' }}>
                {r.label}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* Search */}
      <div
        className="flex items-center gap-2 rounded-xl px-3 py-2.5"
        style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
      >
        <Search size={15} style={{ color: 'var(--text-muted)' }} />
        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Buscar usuario..."
          className="flex-1 bg-transparent text-sm outline-none"
          style={{ color: 'var(--text-primary)' }}
        />
      </div>

      {/* Table */}
      <div
        className="overflow-hidden rounded-2xl"
        style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
      >
        <table className="w-full">
          <thead>
            <tr style={{ borderBottom: '1px solid var(--border)' }}>
              {['Usuario', 'Rol', 'Estado', 'Último acceso', 'Creado', ''].map((h) => (
                <th
                  key={h}
                  className="px-4 py-3 text-left text-xs font-semibold tracking-wide uppercase"
                  style={{ color: 'var(--text-muted)' }}
                >
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {filtered.map((u, i) => {
              const rc = roleConfig[u.role]
              return (
                <motion.tr
                  key={u.id}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: i * 0.05 }}
                  className="border-b transition-colors last:border-b-0"
                  style={{ borderColor: 'var(--border)' }}
                  onMouseEnter={(e) => (e.currentTarget.style.background = 'var(--surface-hover)')}
                  onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
                >
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-3">
                      <div
                        className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-full text-sm font-black"
                        style={{
                          background: 'linear-gradient(135deg,var(--accent),var(--detail))',
                          color: 'var(--text-on-primary)',
                        }}
                      >
                        {u.name
                          .split(' ')
                          .map((n) => n[0])
                          .join('')
                          .slice(0, 2)}
                      </div>
                      <div>
                        <p
                          className="text-sm font-semibold"
                          style={{ color: 'var(--text-primary)' }}
                        >
                          {u.name}
                        </p>
                        <p className="text-xs" style={{ color: 'var(--text-muted)' }}>
                          {u.email}
                        </p>
                      </div>
                    </div>
                  </td>
                  <td className="px-4 py-3">
                    <span
                      className="flex items-center gap-1.5 text-xs font-semibold"
                      style={{ color: rc.color }}
                    >
                      <rc.icon size={12} />
                      {rc.label}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <span
                      className="rounded-full px-2 py-0.5 text-xs font-bold"
                      style={{
                        background: `${u.status === 'ACTIVE' ? 'var(--success)' : 'var(--text-muted)'}18`,
                        color: u.status === 'ACTIVE' ? 'var(--success)' : 'var(--text-muted)',
                      }}
                    >
                      {u.status === 'ACTIVE' ? 'Activo' : 'Inactivo'}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-xs" style={{ color: 'var(--text-muted)' }}>
                    {u.lastLogin}
                  </td>
                  <td className="px-4 py-3 text-xs" style={{ color: 'var(--text-muted)' }}>
                    {u.createdAt}
                  </td>
                  <td className="relative px-4 py-3">
                    <button
                      onClick={() => setOpenMenu(openMenu === u.id ? null : u.id)}
                      className="rounded-lg p-1.5"
                      style={{ color: 'var(--text-muted)' }}
                    >
                      <MoreVertical size={16} />
                    </button>
                    <AnimatePresence>
                      {openMenu === u.id && (
                        <motion.div
                          initial={{ opacity: 0, scale: 0.9 }}
                          animate={{ opacity: 1, scale: 1 }}
                          exit={{ opacity: 0, scale: 0.9 }}
                          className="absolute right-0 z-10 w-40 rounded-xl py-1 shadow-lg"
                          style={{
                            background: 'var(--surface)',
                            border: '1px solid var(--border)',
                            top: '100%',
                          }}
                        >
                          {[
                            { label: '✏️ Editar', fn: () => openEdit(u) },
                            {
                              label: u.status === 'ACTIVE' ? '⏸ Desactivar' : '▶ Activar',
                              fn: () => toggleStatus(u),
                            },
                            { label: '🗑 Eliminar', fn: () => deleteUser(u), danger: true },
                          ].map((item) => (
                            <button
                              key={item.label}
                              onClick={item.fn}
                              className="block w-full px-4 py-2 text-left text-sm transition-colors"
                              style={{
                                color: item.danger ? 'var(--danger)' : 'var(--text-secondary)',
                              }}
                              onMouseEnter={(e) =>
                                (e.currentTarget.style.background = 'var(--surface-hover)')
                              }
                              onMouseLeave={(e) =>
                                (e.currentTarget.style.background = 'transparent')
                              }
                            >
                              {item.label}
                            </button>
                          ))}
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </td>
                </motion.tr>
              )
            })}
          </tbody>
        </table>
      </div>

      {/* Modal */}
      <AnimatePresence>
        {showModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4"
            style={{ background: 'var(--overlay)', backdropFilter: 'blur(6px)' }}
            onClick={() => setShowModal(false)}
          >
            <motion.div
              initial={{ scale: 0.9 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0.9 }}
              className="w-full max-w-md rounded-2xl p-6"
              onClick={(e) => e.stopPropagation()}
              style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
            >
              <div className="mb-5 flex items-center justify-between">
                <h2 className="text-lg font-bold" style={{ color: 'var(--text-primary)' }}>
                  {editing ? 'Editar Usuario' : 'Nuevo Usuario'}
                </h2>
                <button onClick={() => setShowModal(false)} style={{ color: 'var(--text-muted)' }}>
                  <X size={18} />
                </button>
              </div>
              <div className="space-y-4">
                {[
                  { label: 'Nombre', key: 'name', placeholder: 'Juan García' },
                  { label: 'Email', key: 'email', placeholder: 'juan@saas.com', type: 'email' },
                ].map((f) => (
                  <div key={f.key}>
                    <label
                      className="mb-1.5 block text-xs font-semibold"
                      style={{ color: 'var(--text-secondary)' }}
                    >
                      {f.label}
                    </label>
                    <input
                      type={f.type ?? 'text'}
                      value={(form as any)[f.key]}
                      onChange={(e) => setForm({ ...form, [f.key]: e.target.value })}
                      placeholder={f.placeholder}
                      className="w-full rounded-xl px-3 py-2.5 text-sm outline-none"
                      style={{
                        background: 'var(--input-bg)',
                        border: '1px solid var(--border)',
                        color: 'var(--text-primary)',
                      }}
                      onFocus={(e) => (e.target.style.borderColor = 'var(--accent)')}
                      onBlur={(e) => (e.target.style.borderColor = 'var(--border)')}
                    />
                  </div>
                ))}
                <div>
                  <label
                    className="mb-1.5 block text-xs font-semibold"
                    style={{ color: 'var(--text-secondary)' }}
                  >
                    Rol
                  </label>
                  <select
                    value={form.role}
                    onChange={(e) => setForm({ ...form, role: e.target.value as Role })}
                    className="w-full rounded-xl px-3 py-2.5 text-sm outline-none"
                    style={{
                      background: 'var(--input-bg)',
                      border: '1px solid var(--border)',
                      color: 'var(--text-primary)',
                    }}
                  >
                    <option value="SUPER_ADMIN">Super Admin</option>
                    <option value="SUPPORT">Soporte</option>
                    <option value="DEVOPS">DevOps</option>
                    <option value="SALES">Ventas</option>
                  </select>
                </div>
              </div>
              <div className="mt-6 flex justify-end gap-3">
                <button
                  onClick={() => setShowModal(false)}
                  className="rounded-xl px-4 py-2 text-sm font-semibold"
                  style={{ background: 'var(--surface-hover)', color: 'var(--text-secondary)' }}
                >
                  Cancelar
                </button>
                <button
                  onClick={save}
                  className="rounded-xl px-4 py-2 text-sm font-semibold"
                  style={{ background: 'var(--accent)', color: 'var(--text-on-primary)' }}
                >
                  {editing ? 'Guardar' : 'Crear'}
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            className="fixed right-6 bottom-6 z-50 rounded-xl px-4 py-3 text-sm font-semibold"
            style={{
              background: 'var(--surface)',
              border: '1px solid var(--border)',
              color: 'var(--text-primary)',
              boxShadow: 'var(--shadow-lg)',
            }}
          >
            ✅ {toast}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

// src/app/features/platform/platform-users.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface PlatformUser {
  id: string; name: string; email: string;
  role: 'SUPER_ADMIN' | 'SUPPORT' | 'DEVOPS' | 'SALES';
  status: 'ACTIVE' | 'INACTIVE';
  lastLogin: string; createdAt: string;
}

@Component({
  selector: 'app-platform-users',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="page">
      <div class="page-header">
        <div>
          <h2 class="page-title">Usuarios de Plataforma</h2>
          <p class="page-sub">Administra los usuarios con acceso al panel de administración</p>
        </div>
        <button class="btn-primary" (click)="openModal()">+ Nuevo Usuario</button>
      </div>

      <!-- Roles info -->
      <div class="roles-row">
        <div *ngFor="let r of roleCards" class="role-card">
          <span class="role-icon">{{ r.icon }}</span>
          <div>
            <div class="role-name">{{ r.role }}</div>
            <div class="role-desc">{{ r.desc }}</div>
          </div>
          <span class="role-count">{{ countByRole(r.role) }}</span>
        </div>
      </div>

      <!-- Search -->
      <div class="search-box">
        <span>🔍</span>
        <input [(ngModel)]="search" placeholder="Buscar usuario..." class="search-input">
      </div>

      <div class="table-card">
        <table class="data-table">
          <thead>
            <tr>
              <th>Usuario</th>
              <th>Rol</th>
              <th>Estado</th>
              <th>Último acceso</th>
              <th>Creado</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let u of filtered" class="table-row">
              <td>
                <div class="user-cell">
                  <div class="u-avatar">{{ u.name[0] }}</div>
                  <div>
                    <div class="u-name">{{ u.name }}</div>
                    <div class="u-email">{{ u.email }}</div>
                  </div>
                </div>
              </td>
              <td><span class="role-badge" [class]="'role-' + u.role">{{ u.role }}</span></td>
              <td><span class="st-badge" [class]="'st-' + u.status">{{ u.status === 'ACTIVE' ? 'Activo' : 'Inactivo' }}</span></td>
              <td><span class="muted">{{ u.lastLogin }}</span></td>
              <td><span class="muted">{{ u.createdAt }}</span></td>
              <td>
                <div class="actions">
                  <button class="act-btn" (click)="editUser(u)" title="Editar">✏️</button>
                  <button class="act-btn" (click)="toggleUser(u)" [title]="u.status === 'ACTIVE' ? 'Desactivar' : 'Activar'">
                    {{ u.status === 'ACTIVE' ? '⏸' : '▶' }}
                  </button>
                  <button class="act-btn delete" (click)="deleteUser(u)" title="Eliminar">🗑</button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Modal -->
    <div class="modal-overlay" *ngIf="showModal" (click)="closeModal()">
      <div class="modal-box" (click)="$event.stopPropagation()">
        <div class="modal-header">
          <h3>{{ editing ? 'Editar Usuario' : 'Nuevo Usuario de Plataforma' }}</h3>
          <button class="modal-close" (click)="closeModal()">✕</button>
        </div>
        <div class="modal-body">
          <div class="form-grid">
            <div class="form-field">
              <label>Nombre completo</label>
              <input [(ngModel)]="form.name" placeholder="Juan García">
            </div>
            <div class="form-field">
              <label>Email</label>
              <input [(ngModel)]="form.email" type="email" placeholder="juan@saas.com">
            </div>
            <div class="form-field">
              <label>Rol</label>
              <select [(ngModel)]="form.role">
                <option value="SUPER_ADMIN">Super Admin</option>
                <option value="SUPPORT">Soporte</option>
                <option value="DEVOPS">DevOps</option>
                <option value="SALES">Ventas</option>
              </select>
            </div>
            <div class="form-field" *ngIf="!editing">
              <label>Contraseña temporal</label>
              <input type="password" [(ngModel)]="form.password" placeholder="••••••••">
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn-ghost" (click)="closeModal()">Cancelar</button>
          <button class="btn-primary" (click)="saveUser()">{{ editing ? 'Guardar' : 'Crear Usuario' }}</button>
        </div>
      </div>
    </div>

    <div class="toast" *ngIf="toast" [class]="'toast-' + toastType">{{ toast }}</div>
  `,
  styles: [`
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    * { box-sizing: border-box; }
    .page { display: flex; flex-direction: column; gap: 1.25rem; font-family: 'Inter', sans-serif; }
    .page-header { display: flex; align-items: flex-start; justify-content: space-between; }
    .page-title { color: #fff; font-size: 1.3rem; font-weight: 700; margin: 0; }
    .page-sub   { color: rgba(255,255,255,0.4); font-size: 0.82rem; margin: 0.25rem 0 0; }

    .btn-primary { background: linear-gradient(135deg,#6c63ff,#48cae4); color:#fff; border:none; border-radius:10px; padding:0.65rem 1.25rem; font-size:0.88rem; font-weight:600; cursor:pointer; font-family:'Inter',sans-serif; transition:all 0.2s; }
    .btn-primary:hover { transform:translateY(-1px); box-shadow:0 6px 20px rgba(108,99,255,0.35); }
    .btn-ghost { background:rgba(255,255,255,0.06); color:rgba(255,255,255,0.7); border:1px solid rgba(255,255,255,0.1); border-radius:10px; padding:0.65rem 1.25rem; font-size:0.88rem; font-weight:600; cursor:pointer; font-family:'Inter',sans-serif; transition:all 0.2s; }

    .roles-row { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px,1fr)); gap: 0.75rem; }
    .role-card {
      background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.07);
      border-radius: 12px; padding: 1rem; display: flex; align-items: center; gap: 0.85rem;
    }
    .role-icon { font-size: 1.4rem; }
    .role-name { color: #fff; font-size: 0.82rem; font-weight: 600; }
    .role-desc { color: rgba(255,255,255,0.4); font-size: 0.72rem; }
    .role-count { margin-left: auto; color: #6c63ff; font-weight: 700; font-size: 1.1rem; }

    .search-box { display:flex; align-items:center; gap:0.5rem; background:rgba(255,255,255,0.05); border:1px solid rgba(255,255,255,0.08); border-radius:10px; padding:0.55rem 1rem; }
    .search-input { background:none; border:none; outline:none; color:#fff; font-size:0.87rem; width:100%; font-family:'Inter',sans-serif; }
    .search-input::placeholder { color:rgba(255,255,255,0.3); }

    .table-card { background:rgba(255,255,255,0.03); border:1px solid rgba(255,255,255,0.07); border-radius:14px; overflow:hidden; }
    .data-table { width:100%; border-collapse:collapse; }
    .data-table th { background:rgba(255,255,255,0.03); color:rgba(255,255,255,0.4); font-size:0.73rem; font-weight:600; letter-spacing:0.5px; text-transform:uppercase; padding:0.85rem 1rem; border-bottom:1px solid rgba(255,255,255,0.06); text-align:left; }
    .data-table td { padding:0.85rem 1rem; border-bottom:1px solid rgba(255,255,255,0.04); vertical-align:middle; }
    .table-row:hover { background:rgba(255,255,255,0.03); }
    .table-row:last-child td { border-bottom:none; }

    .user-cell { display:flex; align-items:center; gap:0.75rem; }
    .u-avatar { width:34px; height:34px; border-radius:50%; background:linear-gradient(135deg,#6c63ff,#48cae4); display:flex; align-items:center; justify-content:center; color:#fff; font-weight:700; font-size:0.85rem; flex-shrink:0; }
    .u-name  { color:#fff; font-size:0.85rem; font-weight:600; }
    .u-email { color:rgba(255,255,255,0.35); font-size:0.72rem; }
    .muted   { color:rgba(255,255,255,0.4); font-size:0.78rem; }

    .role-badge, .st-badge { padding:0.22rem 0.6rem; border-radius:20px; font-size:0.7rem; font-weight:700; }
    .role-SUPER_ADMIN { background:rgba(250,204,21,0.15); color:#facc15; }
    .role-SUPPORT     { background:rgba(96,165,250,0.15);  color:#60a5fa; }
    .role-DEVOPS      { background:rgba(52,211,153,0.15);  color:#34d399; }
    .role-SALES       { background:rgba(251,146,60,0.15);  color:#fb923c; }
    .st-ACTIVE   { background:rgba(34,197,94,0.15); color:#4ade80; }
    .st-INACTIVE { background:rgba(107,114,128,0.15); color:#9ca3af; }

    .actions { display:flex; gap:0.35rem; }
    .act-btn { width:30px; height:30px; border-radius:7px; border:none; cursor:pointer; font-size:0.78rem; display:flex; align-items:center; justify-content:center; background:rgba(255,255,255,0.05); transition:all 0.15s; }
    .act-btn.delete { background:rgba(239,68,68,0.1); }
    .act-btn:hover { transform:scale(1.1); filter:brightness(1.3); }

    .modal-overlay { position:fixed; inset:0; background:rgba(0,0,0,0.65); backdrop-filter:blur(6px); display:flex; align-items:center; justify-content:center; z-index:100; padding:1rem; }
    .modal-box { background:#181828; border:1px solid rgba(255,255,255,0.1); border-radius:18px; width:100%; max-width:480px; animation:popIn 0.25s ease; }
    @keyframes popIn { from{transform:scale(0.94);opacity:0} to{transform:scale(1);opacity:1} }
    .modal-header { display:flex; align-items:center; justify-content:space-between; padding:1.25rem 1.5rem; border-bottom:1px solid rgba(255,255,255,0.07); }
    .modal-header h3 { color:#fff; font-size:1rem; font-weight:700; margin:0; }
    .modal-close { background:none; border:none; color:rgba(255,255,255,0.4); font-size:1rem; cursor:pointer; padding:0.25rem; }
    .modal-body { padding:1.5rem; }
    .modal-footer { padding:1rem 1.5rem; border-top:1px solid rgba(255,255,255,0.07); display:flex; justify-content:flex-end; gap:0.75rem; }
    .form-grid { display:grid; grid-template-columns:1fr 1fr; gap:1rem; }
    .form-field { display:flex; flex-direction:column; gap:0.4rem; }
    .form-field label { color:rgba(255,255,255,0.6); font-size:0.8rem; font-weight:500; }
    .form-field input, .form-field select { background:rgba(255,255,255,0.06); border:1px solid rgba(255,255,255,0.1); border-radius:9px; padding:0.6rem 0.85rem; color:#fff; font-size:0.87rem; outline:none; transition:all 0.2s; font-family:'Inter',sans-serif; }
    .form-field input:focus, .form-field select:focus { border-color:#6c63ff; box-shadow:0 0 0 3px rgba(108,99,255,0.2); }
    .form-field select option { background:#181828; }

    .toast { position:fixed; bottom:1.5rem; right:1.5rem; padding:0.75rem 1.25rem; border-radius:10px; font-size:0.85rem; font-weight:600; font-family:'Inter',sans-serif; z-index:200; }
    .toast-success { background:#166534; color:#4ade80; border:1px solid rgba(74,222,128,0.3); }
    .toast-error   { background:#7f1d1d; color:#f87171; border:1px solid rgba(248,113,113,0.3); }
  `]
})
export class PlatformUsersComponent {
  search = ''; showModal = false; editing = false; editingId = '';
  toast = ''; toastType = 'success';
  form = { name: '', email: '', role: 'SUPPORT', password: '' };

  roleCards = [
    { icon: '👑', role: 'SUPER_ADMIN', desc: 'Acceso total' },
    { icon: '🎧', role: 'SUPPORT',     desc: 'Soporte a clientes' },
    { icon: '🛠',  role: 'DEVOPS',     desc: 'Infraestructura' },
    { icon: '📈', role: 'SALES',       desc: 'Ventas y demos' },
  ];

  users: PlatformUser[] = [
    { id:'1', name:'Carlos Herrera',  email:'carlos@saas.com',   role:'SUPER_ADMIN', status:'ACTIVE',   lastLogin:'Hoy, 12:36',     createdAt:'01 Ene 2026' },
    { id:'2', name:'Ana Martínez',    email:'ana@saas.com',      role:'SUPPORT',     status:'ACTIVE',   lastLogin:'Hoy, 09:14',     createdAt:'15 Ene 2026' },
    { id:'3', name:'Luis Ramírez',    email:'luis@saas.com',     role:'DEVOPS',      status:'ACTIVE',   lastLogin:'Ayer, 22:05',    createdAt:'20 Ene 2026' },
    { id:'4', name:'María Torres',    email:'maria@saas.com',    role:'SALES',       status:'ACTIVE',   lastLogin:'Hace 2 días',    createdAt:'01 Feb 2026' },
    { id:'5', name:'Pedro Gómez',     email:'pedro@saas.com',    role:'SUPPORT',     status:'INACTIVE', lastLogin:'Hace 2 semanas', createdAt:'10 Feb 2026' },
  ];

  countByRole(role: string): number { return this.users.filter(u => u.role === role).length; }

  get filtered(): PlatformUser[] {
    return this.users.filter(u =>
      u.name.toLowerCase().includes(this.search.toLowerCase()) ||
      u.email.toLowerCase().includes(this.search.toLowerCase())
    );
  }

  openModal(): void { this.form = { name:'', email:'', role:'SUPPORT', password:'' }; this.editing = false; this.showModal = true; }
  closeModal(): void { this.showModal = false; }
  editUser(u: PlatformUser): void { this.form = { name:u.name, email:u.email, role:u.role, password:'' }; this.editingId = u.id; this.editing = true; this.showModal = true; }
  toggleUser(u: PlatformUser): void { u.status = u.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'; this.showToast(`${u.name} ${u.status === 'ACTIVE' ? 'activado' : 'desactivado'}`, 'success'); }
  deleteUser(u: PlatformUser): void { this.users = this.users.filter(x => x.id !== u.id); this.showToast(`${u.name} eliminado`, 'error'); }
  saveUser(): void {
    if (this.editing) { const u = this.users.find(x => x.id === this.editingId); if (u) { u.name = this.form.name; u.email = this.form.email; u.role = this.form.role as any; } }
    else { this.users.unshift({ id: Date.now().toString(), name: this.form.name, email: this.form.email, role: this.form.role as any, status: 'ACTIVE', lastLogin: 'Nunca', createdAt: 'Hoy' }); }
    this.closeModal(); this.showToast(this.editing ? 'Cambios guardados' : 'Usuario creado', 'success');
  }
  private showToast(msg: string, type: string): void { this.toast = msg; this.toastType = type; setTimeout(() => this.toast = '', 3000); }
}
