// src/app/features/platform/platform-settings.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-platform-settings',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="page">
      <div class="page-header">
        <div>
          <h2 class="page-title">Configuración de Plataforma</h2>
          <p class="page-sub">Ajustes globales del sistema SaaS MultiGym</p>
        </div>
        <button class="btn-primary" (click)="save()">Guardar cambios</button>
      </div>

      <div class="settings-grid">
        <!-- General -->
        <div class="settings-card">
          <div class="card-header"><span class="card-icon">🏢</span><h3>General</h3></div>
          <div class="form-fields">
            <div class="form-field"><label>Nombre de la plataforma</label><input [(ngModel)]="cfg.platformName"></div>
            <div class="form-field"><label>Dominio principal</label><input [(ngModel)]="cfg.domain"></div>
            <div class="form-field"><label>Email de soporte</label><input type="email" [(ngModel)]="cfg.supportEmail"></div>
            <div class="form-field"><label>Zona horaria</label>
              <select [(ngModel)]="cfg.timezone">
                <option>America/Mexico_City</option>
                <option>America/New_York</option>
                <option>Europe/Madrid</option>
              </select>
            </div>
          </div>
        </div>

        <!-- Trial -->
        <div class="settings-card">
          <div class="card-header"><span class="card-icon">⏱️</span><h3>Período Trial</h3></div>
          <div class="form-fields">
            <div class="form-field"><label>Duración del trial (días)</label><input type="number" [(ngModel)]="cfg.trialDays"></div>
            <div class="form-field"><label>Plan por defecto en trial</label>
              <select [(ngModel)]="cfg.defaultTrialPlan">
                <option value="STARTER">Starter</option>
                <option value="PRO">Pro</option>
              </select>
            </div>
            <div class="toggle-field">
              <div><div class="tgl-label">Requerir tarjeta para trial</div><div class="tgl-sub">Si está activo, se exige método de pago al registrarse</div></div>
              <div class="toggle" [class.on]="cfg.requireCard" (click)="cfg.requireCard = !cfg.requireCard"><div class="toggle-knob"></div></div>
            </div>
            <div class="toggle-field">
              <div><div class="tgl-label">Email de expiración</div><div class="tgl-sub">Notificar al tenant 3 días antes de que expire el trial</div></div>
              <div class="toggle" [class.on]="cfg.trialEmail" (click)="cfg.trialEmail = !cfg.trialEmail"><div class="toggle-knob"></div></div>
            </div>
          </div>
        </div>

        <!-- Security -->
        <div class="settings-card">
          <div class="card-header"><span class="card-icon">🔐</span><h3>Seguridad</h3></div>
          <div class="form-fields">
            <div class="form-field"><label>Tiempo de sesión (minutos)</label><input type="number" [(ngModel)]="cfg.sessionTimeout"></div>
            <div class="toggle-field">
              <div><div class="tgl-label">Autenticación 2FA</div><div class="tgl-sub">Requerir 2FA para acceso al panel de plataforma</div></div>
              <div class="toggle" [class.on]="cfg.twoFactor" (click)="cfg.twoFactor = !cfg.twoFactor"><div class="toggle-knob"></div></div>
            </div>
            <div class="toggle-field">
              <div><div class="tgl-label">Registro de IPs</div><div class="tgl-sub">Guardar IP en cada acción del log de auditoría</div></div>
              <div class="toggle" [class.on]="cfg.logIp" (click)="cfg.logIp = !cfg.logIp"><div class="toggle-knob"></div></div>
            </div>
          </div>
        </div>

        <!-- Notifications -->
        <div class="settings-card">
          <div class="card-header"><span class="card-icon">🔔</span><h3>Notificaciones</h3></div>
          <div class="form-fields">
            <div class="toggle-field">
              <div><div class="tgl-label">Nuevo tenant</div><div class="tgl-sub">Notificar al crear un nuevo gimnasio</div></div>
              <div class="toggle" [class.on]="cfg.notifyNew" (click)="cfg.notifyNew = !cfg.notifyNew"><div class="toggle-knob"></div></div>
            </div>
            <div class="toggle-field">
              <div><div class="tgl-label">Pago fallido</div><div class="tgl-sub">Alerta cuando falla un cobro</div></div>
              <div class="toggle" [class.on]="cfg.notifyFail" (click)="cfg.notifyFail = !cfg.notifyFail"><div class="toggle-knob"></div></div>
            </div>
            <div class="toggle-field">
              <div><div class="tgl-label">Reporte semanal</div><div class="tgl-sub">Enviar resumen semanal por email</div></div>
              <div class="toggle" [class.on]="cfg.weeklyReport" (click)="cfg.weeklyReport = !cfg.weeklyReport"><div class="toggle-knob"></div></div>
            </div>
            <div class="form-field"><label>Email para alertas</label><input type="email" [(ngModel)]="cfg.alertEmail"></div>
          </div>
        </div>
      </div>

      <!-- Danger zone -->
      <div class="danger-zone">
        <div class="danger-header">
          <span class="danger-icon">⚠️</span>
          <div><h3>Zona de peligro</h3><p>Estas acciones son irreversibles. Úsalas con precaución.</p></div>
        </div>
        <div class="danger-actions">
          <button class="danger-btn">🗑 Limpiar logs de auditoría</button>
          <button class="danger-btn">🔄 Resetear configuración</button>
          <button class="danger-btn red">⛔ Poner plataforma en mantenimiento</button>
        </div>
      </div>
    </div>

    <div class="toast" *ngIf="saved">✅ Configuración guardada</div>
  `,
  styles: [`
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    * { box-sizing:border-box; }
    .page { display:flex; flex-direction:column; gap:1.25rem; font-family:'Inter',sans-serif; }
    .page-header { display:flex; align-items:flex-start; justify-content:space-between; }
    .page-title { color:#fff; font-size:1.3rem; font-weight:700; margin:0; }
    .page-sub   { color:rgba(255,255,255,0.4); font-size:0.82rem; margin:0.25rem 0 0; }
    .btn-primary { background:linear-gradient(135deg,#6c63ff,#48cae4); color:#fff; border:none; border-radius:10px; padding:0.65rem 1.25rem; font-size:0.88rem; font-weight:600; cursor:pointer; font-family:'Inter',sans-serif; transition:all 0.2s; }
    .btn-primary:hover { transform:translateY(-1px); box-shadow:0 6px 20px rgba(108,99,255,0.35); }

    .settings-grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(340px,1fr)); gap:1rem; }
    .settings-card { background:rgba(255,255,255,0.03); border:1px solid rgba(255,255,255,0.07); border-radius:14px; padding:1.5rem; }
    .card-header { display:flex; align-items:center; gap:0.75rem; margin-bottom:1.25rem; }
    .card-icon { font-size:1.2rem; }
    .card-header h3 { color:#fff; font-size:0.95rem; font-weight:700; margin:0; }

    .form-fields { display:flex; flex-direction:column; gap:1rem; }
    .form-field { display:flex; flex-direction:column; gap:0.4rem; }
    .form-field label { color:rgba(255,255,255,0.55); font-size:0.78rem; font-weight:500; }
    .form-field input, .form-field select { background:rgba(255,255,255,0.06); border:1px solid rgba(255,255,255,0.1); border-radius:9px; padding:0.6rem 0.85rem; color:#fff; font-size:0.87rem; outline:none; transition:all 0.2s; font-family:'Inter',sans-serif; }
    .form-field input:focus, .form-field select:focus { border-color:#6c63ff; box-shadow:0 0 0 3px rgba(108,99,255,0.2); }
    .form-field select option { background:#181828; }

    /* Toggle */
    .toggle-field { display:flex; align-items:center; justify-content:space-between; gap:1rem; padding:0.5rem 0; }
    .tgl-label { color:rgba(255,255,255,0.8); font-size:0.85rem; font-weight:500; margin-bottom:0.15rem; }
    .tgl-sub   { color:rgba(255,255,255,0.35); font-size:0.72rem; }
    .toggle { width:44px; height:24px; border-radius:100px; background:rgba(255,255,255,0.1); cursor:pointer; position:relative; transition:background 0.3s; flex-shrink:0; }
    .toggle.on { background:linear-gradient(135deg,#6c63ff,#48cae4); }
    .toggle-knob { position:absolute; top:3px; left:3px; width:18px; height:18px; border-radius:50%; background:#fff; transition:transform 0.3s; box-shadow:0 1px 4px rgba(0,0,0,0.3); }
    .toggle.on .toggle-knob { transform:translateX(20px); }

    /* Danger zone */
    .danger-zone { background:rgba(239,68,68,0.05); border:1px solid rgba(239,68,68,0.2); border-radius:14px; padding:1.5rem; }
    .danger-header { display:flex; align-items:center; gap:1rem; margin-bottom:1.25rem; }
    .danger-icon { font-size:1.5rem; }
    .danger-header h3 { color:#f87171; font-size:0.95rem; font-weight:700; margin:0 0 0.2rem; }
    .danger-header p  { color:rgba(255,255,255,0.4); font-size:0.78rem; margin:0; }
    .danger-actions { display:flex; gap:0.75rem; flex-wrap:wrap; }
    .danger-btn { background:rgba(239,68,68,0.08); border:1px solid rgba(239,68,68,0.2); color:rgba(255,255,255,0.65); border-radius:10px; padding:0.6rem 1rem; font-size:0.82rem; font-weight:500; cursor:pointer; font-family:'Inter',sans-serif; transition:all 0.2s; }
    .danger-btn:hover { background:rgba(239,68,68,0.15); color:#fff; }
    .danger-btn.red { background:rgba(239,68,68,0.15); color:#f87171; border-color:rgba(239,68,68,0.4); }

    .toast { position:fixed; bottom:1.5rem; right:1.5rem; background:#166534; color:#4ade80; border:1px solid rgba(74,222,128,0.3); padding:0.75rem 1.25rem; border-radius:10px; font-size:0.85rem; font-weight:600; z-index:200; font-family:'Inter',sans-serif; }
  `]
})
export class PlatformSettingsComponent {
  saved = false;

  cfg = {
    platformName: 'MultiGym Platform',
    domain: 'multigym.com',
    supportEmail: 'soporte@multigym.com',
    timezone: 'America/Mexico_City',
    trialDays: 14,
    defaultTrialPlan: 'STARTER',
    requireCard: false,
    trialEmail: true,
    sessionTimeout: 480,
    twoFactor: false,
    logIp: true,
    notifyNew: true,
    notifyFail: true,
    weeklyReport: false,
    alertEmail: 'admin@saas.com',
  };

  save(): void {
    this.saved = true;
    setTimeout(() => this.saved = false, 3000);
  }
}

// src/pages/platform/PlatformSettings.tsx
import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Save, Globe, Lock, Bell, AlertTriangle, RefreshCw } from "lucide-react"

export default function PlatformSettings() {
  const [saved, setSaved] = useState(false)
  const [cfg, setCfg] = useState({
    platformName: "MultiGym Platform", domain: "multigym.com", supportEmail: "soporte@multigym.com", timezone: "America/Mexico_City",
    trialDays: 14, defaultTrialPlan: "STARTER", requireCard: false, trialEmail: true,
    sessionTimeout: 480, twoFactor: false, logIp: true,
    notifyNew: true, notifyFail: true, weeklyReport: false, alertEmail: "admin@saas.com",
  })

  const save = () => { setSaved(true); setTimeout(() => setSaved(false), 3000) }

  const Toggle = ({ label, sub, checked, onChange }: any) => (
    <div className="flex items-center justify-between py-2">
      <div>
        <p className="text-sm font-semibold" style={{ color: "var(--text-primary)" }}>{label}</p>
        <p className="text-xs" style={{ color: "var(--text-muted)" }}>{sub}</p>
      </div>
      <button
        onClick={onChange}
        className="w-11 h-6 rounded-full relative transition-colors"
        style={{ background: checked ? "var(--accent)" : "rgba(255,255,255,0.1)" }}
      >
        <div
          className="absolute top-1 left-1 w-4 h-4 rounded-full bg-white transition-transform"
          style={{ transform: checked ? "translateX(20px)" : "translateX(0)" }}
        />
      </button>
    </div>
  )

  const Input = ({ label, type = "text", ...props }: any) => (
    <div>
      <label className="block text-xs font-semibold mb-1.5" style={{ color: "var(--text-secondary)" }}>{label}</label>
      <input
        type={type} {...props}
        className="w-full px-3 py-2.5 rounded-xl text-sm outline-none transition-all"
        style={{ background: "rgba(255,255,255,0.05)", border: "1px solid var(--border)", color: "var(--text-primary)" }}
        onFocus={(e) => (e.target.style.borderColor = "var(--accent)")}
        onBlur={(e) => (e.target.style.borderColor = "var(--border)")}
      />
    </div>
  )

  const Select = ({ label, options, ...props }: any) => (
    <div>
      <label className="block text-xs font-semibold mb-1.5" style={{ color: "var(--text-secondary)" }}>{label}</label>
      <select
        {...props}
        className="w-full px-3 py-2.5 rounded-xl text-sm outline-none transition-all"
        style={{ background: "rgba(255,255,255,0.05)", border: "1px solid var(--border)", color: "var(--text-primary)" }}
      >
        {options.map((o: any) => <option key={o.value} value={o.value} style={{ background: "var(--surface)" }}>{o.label}</option>)}
      </select>
    </div>
  )

  const Card = ({ icon: Icon, title, children }: any) => (
    <div className="p-6 rounded-2xl" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
      <div className="flex items-center gap-3 mb-6 pb-4" style={{ borderBottom: "1px solid var(--border)" }}>
        <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: "rgba(255,255,255,0.05)", color: "var(--text-secondary)" }}>
          <Icon size={16} />
        </div>
        <h3 className="font-bold text-sm" style={{ color: "var(--text-primary)" }}>{title}</h3>
      </div>
      <div className="space-y-4">
        {children}
      </div>
    </div>
  )

  return (
    <div className="space-y-6 pb-12 relative">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black" style={{ color: "var(--text-primary)", fontFamily: "var(--font-heading)" }}>Configuración de Plataforma</h1>
          <p className="text-sm mt-0.5" style={{ color: "var(--text-muted)" }}>Ajustes globales del sistema SaaS</p>
        </div>
        <button
          onClick={save}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl font-bold text-sm transition-transform hover:-translate-y-0.5"
          style={{ background: "linear-gradient(135deg, var(--accent), var(--detail))", color: "#fff", boxShadow: "0 10px 20px rgba(0,0,255,0.2)" }}
        >
          <Save size={16} /> Guardar Cambios
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card icon={Globe} title="General">
          <Input label="Nombre de la plataforma" value={cfg.platformName} onChange={(e:any)=>setCfg({...cfg, platformName:e.target.value})} />
          <Input label="Dominio principal" value={cfg.domain} onChange={(e:any)=>setCfg({...cfg, domain:e.target.value})} />
          <Input label="Email de soporte" type="email" value={cfg.supportEmail} onChange={(e:any)=>setCfg({...cfg, supportEmail:e.target.value})} />
          <Select label="Zona horaria" value={cfg.timezone} onChange={(e:any)=>setCfg({...cfg, timezone:e.target.value})}
            options={[{label:"America/Mexico_City",value:"America/Mexico_City"},{label:"America/New_York",value:"America/New_York"},{label:"Europe/Madrid",value:"Europe/Madrid"}]} />
        </Card>

        <Card icon={Clock} title="Período Trial">
          <Input label="Duración del trial (días)" type="number" value={cfg.trialDays} onChange={(e:any)=>setCfg({...cfg, trialDays:e.target.value})} />
          <Select label="Plan por defecto en trial" value={cfg.defaultTrialPlan} onChange={(e:any)=>setCfg({...cfg, defaultTrialPlan:e.target.value})}
            options={[{label:"Starter",value:"STARTER"},{label:"Pro",value:"PRO"}]} />
          <div className="pt-2">
            <Toggle label="Requerir tarjeta" sub="Exigir método de pago al registrarse" checked={cfg.requireCard} onChange={()=>setCfg({...cfg, requireCard:!cfg.requireCard})} />
            <Toggle label="Email de expiración" sub="Notificar 3 días antes de expirar" checked={cfg.trialEmail} onChange={()=>setCfg({...cfg, trialEmail:!cfg.trialEmail})} />
          </div>
        </Card>

        <Card icon={Lock} title="Seguridad">
          <Input label="Tiempo de sesión (minutos)" type="number" value={cfg.sessionTimeout} onChange={(e:any)=>setCfg({...cfg, sessionTimeout:e.target.value})} />
          <div className="pt-2">
            <Toggle label="Autenticación 2FA" sub="Requerir 2FA para panel plataforma" checked={cfg.twoFactor} onChange={()=>setCfg({...cfg, twoFactor:!cfg.twoFactor})} />
            <Toggle label="Registro de IPs" sub="Guardar IP en log de auditoría" checked={cfg.logIp} onChange={()=>setCfg({...cfg, logIp:!cfg.logIp})} />
          </div>
        </Card>

        <Card icon={Bell} title="Notificaciones">
          <Input label="Email para alertas" type="email" value={cfg.alertEmail} onChange={(e:any)=>setCfg({...cfg, alertEmail:e.target.value})} />
          <div className="pt-2">
            <Toggle label="Nuevo tenant" sub="Alerta al crear gimnasio" checked={cfg.notifyNew} onChange={()=>setCfg({...cfg, notifyNew:!cfg.notifyNew})} />
            <Toggle label="Pago fallido" sub="Alerta cuando falla un cobro" checked={cfg.notifyFail} onChange={()=>setCfg({...cfg, notifyFail:!cfg.notifyFail})} />
            <Toggle label="Reporte semanal" sub="Enviar resumen semanal" checked={cfg.weeklyReport} onChange={()=>setCfg({...cfg, weeklyReport:!cfg.weeklyReport})} />
          </div>
        </Card>
      </div>

      {/* Danger Zone */}
      <div className="p-6 rounded-2xl border" style={{ background: "rgba(239,68,68,0.03)", borderColor: "rgba(239,68,68,0.2)" }}>
        <div className="flex items-center gap-3 mb-6">
          <AlertTriangle size={20} style={{ color: "var(--danger)" }} />
          <div>
            <h3 className="font-bold text-sm" style={{ color: "var(--danger)" }}>Zona de Peligro</h3>
            <p className="text-xs" style={{ color: "var(--text-muted)" }}>Estas acciones son irreversibles.</p>
          </div>
        </div>
        <div className="flex flex-wrap gap-3">
          <button className="px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 transition-colors hover:bg-white/5" style={{ color: "var(--text-secondary)", border: "1px solid var(--border)" }}>
            <RefreshCw size={14} /> Resetear Configuración
          </button>
          <button className="px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 transition-colors hover:bg-red-500/10" style={{ color: "var(--danger)", border: "1px solid rgba(239,68,68,0.3)" }}>
            <AlertTriangle size={14} /> Poner plataforma en mantenimiento
          </button>
        </div>
      </div>

      <AnimatePresence>
        {saved && (
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 20 }}
            className="fixed bottom-6 right-6 px-4 py-3 rounded-xl text-sm font-semibold z-50 flex items-center gap-2"
            style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--text-primary)", boxShadow: "var(--shadow-lg)" }}>
            <span style={{ color: "var(--success)" }}>✔</span> Configuración guardada correctamente
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
